spring:
  profiles:
    active: local
    include:
      - domain
      - external
      - oauth

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

token:
  access_token:
    expiration_time: 86400000 #하루
  refresh_token:
    expiration_time: 604800000 #30일
  secret: secret
